version: "3.2"
services:
  web:
    image: payant
    build: .
    container_name: payant
    ports:
      - 3000
    env_file: .env
    volumes:
      - ".:/src"
    depends_on:
      - mysql
  mysql:
    container_name: payant_mysql
    image: mysql:8.0
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: "payant"

